/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import models.Kelas;
import models.Nilai;
import services.SiswaService;

/**
 *
 * @author User
 */
public class PrintRaport extends javax.swing.JFrame {

    /**
     * Creates new form Raport
     */
    Nilai nilai;

    public PrintRaport(Nilai nilai) {
        initComponents();
        this.nilai = nilai;
        setValue();
        setResizable(false);
        setLocationRelativeTo(this);
    }

    public void setValue() {
        Kelas kelas = new SiswaService().getKelas(nilai.getSiswa().getNis());
        lblNis.setText(nilai.getSiswa().getNis());
        lblNama.setText(nilai.getSiswa().getNama());
        lblKelas.setText(kelas.getNama());
        lblTingkat.setText(String.valueOf(kelas.getTingkat()));
        lblMataPelajaran.setText(nilai.getMataPelajaran().getNama());
        lblNilaiTugas.setText(String.valueOf(nilai.getNilaiTugas()));
        lblNilaiKuis.setText(String.valueOf(nilai.getNilaiKuis()));
        lblNilaiUTS.setText(String.valueOf(nilai.getNilaiUTS()));
        lblNilaiUAS.setText(String.valueOf(nilai.getNilaiUAS()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRaport = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNis = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblKelas = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTingkat = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblMataPelajaran = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblNilaiTugas = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblNilaiKuis = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblNilaiUTS = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblNilaiUAS = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelRaport.setBackground(new java.awt.Color(255, 255, 255));
        panelRaport.setMaximumSize(new java.awt.Dimension(128, 120));
        panelRaport.setPreferredSize(new java.awt.Dimension(420, 594));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RAPORT SMK NEGERI 1 GRYFFINDOR");

        lblNis.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblNis.setText("DIGANTI NIS");

        lblNama.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblNama.setText("DIGANTI NAMA");

        lblKelas.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblKelas.setText("DIGANTI KELAS");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setText("NIS:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setText("NAMA:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText("KELAS:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setText("TINGKAT:");

        lblTingkat.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTingkat.setText("DIGANTI TINGKAT");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel10.setText("MATA PELAJARAN: ");

        lblMataPelajaran.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblMataPelajaran.setText("DIGANTI MATA PELAJARAN");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel12.setText("NILAI TUGAS:");

        lblNilaiTugas.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblNilaiTugas.setText("DIGANTI TUGAS");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel14.setText("NILAI KUIS");

        lblNilaiKuis.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblNilaiKuis.setText("DIGANTI KUIS");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel16.setText("NILAI UTS:");

        lblNilaiUTS.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblNilaiUTS.setText("DIGANTI UTS");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel18.setText("NILAI UAS:");

        lblNilaiUAS.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblNilaiUAS.setText("DIGANTI UAS");

        javax.swing.GroupLayout panelRaportLayout = new javax.swing.GroupLayout(panelRaport);
        panelRaport.setLayout(panelRaportLayout);
        panelRaportLayout.setHorizontalGroup(
            panelRaportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRaportLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelRaportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRaportLayout.createSequentialGroup()
                        .addGroup(panelRaportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18))
                        .addGap(16, 16, 16)
                        .addGroup(panelRaportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRaportLayout.createSequentialGroup()
                                .addGroup(panelRaportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNilaiUAS)
                                    .addComponent(lblNilaiUTS)
                                    .addComponent(lblNilaiKuis)
                                    .addComponent(lblNilaiTugas))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelRaportLayout.createSequentialGroup()
                                .addComponent(lblMataPelajaran)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panelRaportLayout.createSequentialGroup()
                        .addGroup(panelRaportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(panelRaportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKelas)
                            .addComponent(lblTingkat))
                        .addGap(212, 224, Short.MAX_VALUE))
                    .addGroup(panelRaportLayout.createSequentialGroup()
                        .addGroup(panelRaportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRaportLayout.createSequentialGroup()
                                .addGroup(panelRaportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(21, 21, 21)
                                .addGroup(panelRaportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNis)
                                    .addComponent(lblNama))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(16, 16, 16))))
        );
        panelRaportLayout.setVerticalGroup(
            panelRaportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRaportLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(panelRaportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNis)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addGroup(panelRaportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(jLabel6))
                .addGap(32, 32, 32)
                .addGroup(panelRaportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKelas)
                    .addComponent(jLabel7))
                .addGap(32, 32, 32)
                .addGroup(panelRaportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblTingkat))
                .addGap(32, 32, 32)
                .addGroup(panelRaportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblMataPelajaran))
                .addGap(32, 32, 32)
                .addGroup(panelRaportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblNilaiTugas))
                .addGap(32, 32, 32)
                .addGroup(panelRaportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblNilaiKuis))
                .addGap(32, 32, 32)
                .addGroup(panelRaportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblNilaiUTS))
                .addGap(32, 32, 32)
                .addGroup(panelRaportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lblNilaiUAS))
                .addGap(25, 25, 25))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnCetak.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnCetak.setText("CETAK PDF");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCetak)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnCetak)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRaport, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelRaport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed

        PrinterJob pj = PrinterJob.getPrinterJob();
        pj.setJobName(" Print Raport Siswa ");

        pj.setPrintable(new Printable() {
            public int print(Graphics pg, PageFormat pf, int pageNum) {
                if (pageNum > 0) {
                    return Printable.NO_SUCH_PAGE;
                }

                Graphics2D g2 = (Graphics2D) pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                panelRaport.paint(g2);
                return Printable.PAGE_EXISTS;
            }
        });
        if (pj.printDialog() == false) {
            return;
        }

        try {
            pj.print();
        } catch (PrinterException ex) {
            System.out.println(ex.getMessage());
        }
        this.dispose();
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintRaport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintRaport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintRaport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintRaport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintRaport(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblKelas;
    private javax.swing.JLabel lblMataPelajaran;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNilaiKuis;
    private javax.swing.JLabel lblNilaiTugas;
    private javax.swing.JLabel lblNilaiUAS;
    private javax.swing.JLabel lblNilaiUTS;
    private javax.swing.JLabel lblNis;
    private javax.swing.JLabel lblTingkat;
    private javax.swing.JPanel panelRaport;
    // End of variables declaration//GEN-END:variables
}
